[ADD]Ticket: Added ticket and seat picker
UlisesHR98/VSTicketSystem pull request #3
Opened 2024-05-07 18:07 UTC by Armin-AH

Created the seat picker component, modified the ticket creation form and connected it to the backend.

2024-05-07 20:33 UTC, UlisesHR98 requested changes

2024-05-07 20:33 UTC, UlisesHR98 commented on src/routes/available-seats.jsx
> +  if (formData.firstName !== '' && formData.lastName !== '' && formData.origin !== '' && formData.destiny !== '' && formData.phoneNumber !== '' && formData.paymentType !== '' &&
What happen if the user put something like 
totalAmount=300 
amountPaid = 400

You need to either add a screen message saying that the amount paid can't be greater than the total amount or let the user put the amount with a final message saying that the client need money back.

2024-05-07 20:33 UTC, UlisesHR98 commented on src/routes/ticket-form.jsx
> +        <button className={props.canSubmit ? 'button' : 'button-disabled'} type="submit">Enviar</button>
You must add a message indicating that the user must select at least one seat. This is because if you complete all the form fields without selecting a seat, the Submit button becomes disabled, but you don't know why.

2024-05-07 20:33 UTC, UlisesHR98 commented on src/hooks/useWindowWidth.js
> +        function handleResize() {
Can you check this view for the Iphone SE?
![image](https://github.com/UlisesHR98/VSTicketSystem/assets/160776178/90fa5623-be89-44cc-9111-d077f6d9ba66)


Try to make that view more responsive

2024-05-08 16:41 UTC, Armin-AH commented on src/routes/available-seats.jsx
> +  if (formData.firstName !== '' && formData.lastName !== '' && formData.origin !== '' && formData.destiny !== '' && formData.phoneNumber !== '' && formData.paymentType !== '' &&
There's a validation for that in the ticket-form. If the amount is in the negatives, the debt will be removed from the form and the submit button will be disabled.

2024-05-08 21:30 UTC, UlisesHR98 approved these changes

2024-05-08 21:37 UTC, merged